<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>30226f90-c710-4da6-b3dd-f2023f9ece2a</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.16.16" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ndgf.Application\ndgf.Application.csproj" />
      <ProjectReference Include="..\ndgf.Infrastructure\ndgf.Infrastructure.csproj" />
    </ItemGroup>

</Project>
